### ISSUE TITLE
Minimum API 26?

### ISSUE THREAD

**Issue by weltonpagassini** [erkutaras/ShowcaseView#10]
When testing receives the error of the minimum version of the API in 26

**Comment by mo-tion** [comment]
Same here. To reproduce, just add the library and run the sample code in onCreate.
Gradle throws the following error:

Invoke-customs are only supported starting with Android O (--min-api 26)
Message{kind=ERROR, text=Invoke-customs are only supported starting with Android O (--min-api 26), sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by erkutaras** [comment]
I have faced this problem, when I had deleted compileOptions from build.gradle of sample project.
To solve this issue, you can add following to **app/build.gradle.**

```gradle
android {
    // ........

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
