### ISSUE TITLE
Do you have  "jar" file as a lib?

### ISSUE THREAD

**Issue by mrHelg** [erkutaras/ShowcaseView#13]
Hello!

Probably, my question is stupid.....
But I still use jar files as libraries. Do you have one?
Thanks in advance,

**Comment by erkutaras** [comment]
Hi,
It is impossible to export android library as a **jar** file. Android libs can be extracted as **aar** file. 
I uploaded library's aar file to remote for you. You can download [library-aar file](http://www.erkutaras.com/downloads/aar/showcase-library-release.aar) and add your project. 
To import aar file to project, you can follow the instructions on this [stackoverflow answer](https://stackoverflow.com/a/38749847) . 
Thanks.
