### ISSUE TITLE
Radius must be > 0 exception

### ISSUE THREAD

**Issue by leandrodmartini** [erkutaras/ShowcaseView#15]
I have this error when I try to initialize ShowcaseView in any fragment passing getApplication() as context.
The error occurs at:
https://github.com/erkutaras/ShowcaseView/blob/3cdb21bfcca2ad5c98a6abdb7d9c306d2338de0d/library/src/main/java/com/erkutaras/showcaseview/ShowcaseView.java#L164

**java.lang.IllegalArgumentException: radius must be > 0**

Is there a working example using this library inside a fragment?

**Comment by erkutaras** [comment]
Can you try to display Showcase in onActivityCreated method with activity context? Because, I haven't gotten any exception when using with fragment like your exception and I didn't repeat it.

**Comment by erkutaras** [comment]
I think this issue can be closed because of any answer. Thanks.
