### ISSUE TITLE
Add Button

### ISSUE THREAD

**Issue by Priyanshi-Z** [erkutaras/ShowcaseView#22]
I am using your library for creating app tour for my application I want to know how can I add two button horizontally like Next .... Previous and want to add listener on those buttons also.How can I do this. And I want to customise there positions also

**Comment by erkutaras** [comment]
If you want to customize description part of the showcase, you can create new layout file with layout_intro_description.xml name. With v1.3.7, I updated ShowcaseView, and now, it can be extended. When you create new class that  extended from ShowcaseView, you can update listener of new button.
