### ISSUE TITLE
Continuous Show the case

### ISSUE THREAD

**Issue by rmbhati** [erkutaras/ShowcaseView#35]
Hi,

I have to show continuous 4 time.
For ex. First case open default then Done click open second case and so on..
so here how to get Done click event show i can call second function

Thank you

**Comment by rmbhati** [comment]
solved

**Comment by Himani2000** [comment]
@rmbhati  how did you solve it can you please share your code?

**Comment by rmbhati** [comment]
change the library

**Comment by rmbhati** [comment]
hh
